# Bug since 10/01/2018
# See http://sunjay.ca/2016/07/25/rust-code-coverage
# See https://github.com/travis-ci/travis-ci/issues/9061
# workaround docker issue (sudo make the build outside a container)
sudo: required
language: rust
cache: cargo
# Dependencies of kcov, used by coverage
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

# run builds for all the trains (and more)
rust:
  - stable

before_script:
  - |
      cargo install --force cargo-travis &&
      export PATH=$HOME/.cargo/bin:$PATH

# the main build
script:
  - |
      cargo build --verbose --all --features travis &&
      cargo test --verbose --all &&
      cargo bench &&
      cargo doc

after_success:
# measure code coverage and upload to coveralls.io
  - cargo coveralls
